# Generated by Django 4.0.1 on 2022-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='сертификат')),
                ('score', models.PositiveSmallIntegerField(default=50, verbose_name='оценка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications', verbose_name='изображение')),
                ('date', models.DateField(verbose_name='дата получения')),
                ('url', models.URLField(default='https://', max_length=255, verbose_name='ссылка на сертификат')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='характер')),
                ('description', models.TextField(max_length=512, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'характер',
                'verbose_name_plural': 'характер',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('surname', models.CharField(max_length=64, verbose_name='фамилия')),
                ('address', models.CharField(default='', max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.EmailField(max_length=64, verbose_name='email')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='фото')),
                ('description', models.TextField(blank=True, max_length=2048, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='учебное заведение')),
                ('degree', models.CharField(max_length=255, verbose_name='ученая степень')),
                ('specialization', models.CharField(max_length=255, verbose_name='специализаия')),
                ('gpa', models.DecimalField(decimal_places=2, default='5.00', max_digits=4, verbose_name='средний балл')),
                ('date_for', models.DateField(verbose_name='дата начала обучения')),
                ('date_to', models.DateField(verbose_name='дата окончания обучения')),
            ],
            options={
                'verbose_name': 'образование',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255, verbose_name='организация')),
                ('position', models.TextField(max_length=255, verbose_name='должность')),
                ('description', models.TextField(max_length=2048, verbose_name='описание')),
                ('date_for', models.DateField(verbose_name='дата начала работы')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='дата окончания работы')),
            ],
            options={
                'verbose_name': 'место работы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='проект')),
                ('description', models.TextField(max_length=512, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='изображение')),
                ('url', models.URLField(default='https://', max_length=255, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='навык')),
                ('description', models.TextField(max_length=512, verbose_name='описание')),
                ('score', models.PositiveSmallIntegerField(default=50, verbose_name='оценка навыка')),
                ('icon', models.CharField(default='fab fa-check-square-o', max_length=64, verbose_name='иконка Font Awesome')),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='соцсеть')),
                ('icon', models.CharField(default='fa fa-check-square-o', max_length=50, verbose_name='иконка Font Awesome')),
                ('url', models.URLField(default='https://', max_length=255, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'соцсеть',
                'verbose_name_plural': 'соцсети',
            },
        ),
    ]
