name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: BUILD TEST containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - uses: actions/checkout@v1
      - name: UP TEST containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

      - uses: actions/checkout@v1
      - name: ERRORS CHECK in TEST containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml logs --tail=50 || grep ERROR
