name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose
        run: sudo docker-compose -f docker-compose.yml up --build
  
  run_tests:
    runs-on: ubuntu-latest
    needs: run_services
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose TEST
        run: sudo docker-compose -f docker-compose.test.yml up --build
  
