name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose TEST stack
      - run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build
